{
 "title": "Go HTTP Metrics by github.com/go-chi/metrics",
 "description": "github.com/go-chi/metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "app",
    "query": {
     "query": "label_values({__name__=~\"http_requests_total|http_client_requests_total\"},app)"
    }
   },
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Server: Incoming HTTP Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Response Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "req/min" } },
   "targets": [
    {
     "expr": "sum by(status) (irate(http_requests_total{app=~\"${app:pipe}\"}[$__rate_interval])*60)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Responses by App",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(app) (irate(http_requests_total{app=~\"${app:pipe}\"}[$__rate_interval])*60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "req/min" } },
   "targets": [
    {
     "expr": "60*sum by(app, endpoint) (\n  rate(http_requests_total{app=~\"${app:pipe}\"}[$__rate_interval])\n)",
     "legendFormat": "{{endpoint}} → {{app}}"
    }
   ]
  },
  {
   "title": "Slowest by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(app, endpoint) (rate(http_request_duration_seconds_sum{app=~\"${app:pipe}\"}[$__range]))\n/\nsum by(app, endpoint) (rate(http_request_duration_seconds_count{app=~\"${app:pipe}\"}[$__range]))",
     "legendFormat": "{{endpoint}} → {{app}}"
    }
   ]
  },
  {
   "title": "Requests In-flight",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n    sum by(proto) (http_requests_inflight{app=~\"${app:pipe}\"})\n    -\n    count by(proto) (http_requests_inflight{app=~\"${app:pipe}\"})\n) > 0",
     "legendFormat": "{{proto}}"
    }
   ]
  },
  {
   "title": "Requests In-flight by App",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "expr": "(\n    sum by(app) (http_requests_inflight{app=~\"${app:pipe}\"})\n    -\n    count by(app) (http_requests_inflight{app=~\"${app:pipe}\"})\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Client: Outgoing HTTP Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Request Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "req/min" } },
   "targets": [
    {
     "expr": "sum by(status) (irate(http_client_requests_total{app=~\"${app:pipe}\"}[$__rate_interval])*60)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests by App",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(app) (irate(http_client_requests_total{app=~\"${app:pipe}\"}[$__rate_interval])*60)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Top Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "req/min" } },
   "targets": [
    {
     "expr": "60*sum by(host) (\n  rate(http_client_requests_total{app=~\"${app:pipe}\",status=~\"2..\"}[$__rate_interval])\n)",
     "legendFormat": "HTTP 200 ← {{host}}"
    }
   ]
  },
  {
   "title": "Top Errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "req/min" } },
   "targets": [
    {
     "expr": "60*sum by(host,status) (\n  rate(http_client_requests_total{app=~\"${app:pipe}\", status!=\"200\"}[$__rate_interval])\n)",
     "legendFormat": "HTTP {{status}} ← {{host}}"
    }
   ]
  },
  {
   "title": "Requests In-flight",
   "type": "stat",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(app) (http_client_requests_inflight{app=~\"${app:pipe}\"}) > 0",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Slowest Requests By Host",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(host,status) (rate(http_client_request_duration_seconds_sum{app=~\"${app:pipe}\"}[$__range]))\n/\nsum by(host,status) (rate(http_client_request_duration_seconds_count{app=~\"${app:pipe}\"}[$__range]))",
     "legendFormat": "HTTP {{status}}  ← {{host}}"
    }
   ]
  }
 ]
}