{
 "title": "Go HTTP Metrics",
 "description": "github.com/go-chi/metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": {
     "query": "label_values(http_requests_total,app)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(http_requests_total,app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Server: Incoming HTTP Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Response Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "req/min" } },
   "targets": [
    {
     "expr": "sum by(status) (irate(http_requests_total{app=\"${app:raw}\"}[$__rate_interval])*60)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Top Requests by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "req/min" } },
   "targets": [
    {
     "expr": "60*sum by(endpoint) (\n  rate(http_requests_total{app=\"${app:raw}\"}[$__rate_interval])\n)",
     "legendFormat": "{{endpoint}} "
    }
   ]
  },
  {
   "title": "Slowest Requests by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(http_request_duration_seconds_sum{app=\"${app:raw}\"}[$__range]))\n/\nsum by(endpoint) (rate(http_request_duration_seconds_count{app=\"${app:raw}\"}[$__range]))",
     "legendFormat": "{{endpoint}} {{status}}"
    }
   ]
  },
  {
   "title": "Requests In-flight by App",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(app) (irate(http_requests_total{app=\"${app:raw}\"}[$__rate_interval])*60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests In-flight",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(app) (http_requests_inflight{app=\"${app:raw}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Client: Outgoing HTTP Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Outgoing Request Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "req/min" } },
   "targets": [
    {
     "expr": "sum by(host,status) (irate(http_client_requests_total{app=\"${app:raw}\"}[$__rate_interval])*60)",
     "legendFormat": "{{host}} HTTP {{status}}"
    }
   ]
  },
  {
   "title": "http.Client Request by Hosts",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host) (http_client_requests_total{app=\"${app:raw}\",status=~\"2.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http.Client Errors by Hosts",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host,status) (http_client_requests_total{app=\"${app:raw}\",status=~\"[45].*\"})",
     "legendFormat": "{{host}} HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Slowest Requests By Host",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(host,status) (rate(http_client_request_duration_seconds_sum{app=\"${app:raw}\"}[$__range]))\n/\nsum by(host,status) (rate(http_client_request_duration_seconds_count{app=\"${app:raw}\"}[$__range]))",
     "legendFormat": "{{host}}{{endpoint}} {{status}}"
    }
   ]
  },
  {
   "title": "Outgoing Requests In-flight",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host) (http_client_requests_inflight{app=\"${app:raw}\"})",
     "legendFormat": "{{app}} {{host}}"
    }
   ]
  }
 ]
}